### ISSUE TITLE
best optimization method

### ISSUE THREAD

**Issue by aeternam7** [tomitomi3/LibOptimization#12]
hi, tomi, your project is really awesome

i'm trying to simulate this R code in vb.net

dp <- garch_test$X__1
llh <- function(par) { mu <- par[1]; omega <- par[2]; alpha <- par[3]; beta <- par[4]; e2 <- (dp-mu)^2;  e2t <- omega + alpha*c(mean(e2), e2[-length(dp)]); s2 <- filter(e2t, beta, "recursive", init = mean(e2)); 0.5*sum( log(2*pi) + log(s2) + e2/s2) }
mu <- mean(dp); omega <- 0.1*var(dp); alpha <- 0.1; beta <- 0.8
par <- c(mu, omega, alpha, beta)
small <- 1e-6
low <- c(-10*abs(mu), small, small, small)
up <- c(10*abs(mu), 100*abs(mu), 1-small, 1-small)
fit <- nlminb(start=par, objective=llh, lower=low, upper=up, control=list(x.tol = 1e-8,trace=0))
names(fit$par) <- c("mu", "omega", "alpha", "beta")
round(fit$par, 6)

nlminb optimization method allows initial parameter values and low/up bound of parameters
it converges really fast

any of your method allows this options?

i tested clsOptDE and gets a really accurate values, but does not converge so fast

thanks in advance

**Comment by tomitomi3** [comment]
Hi. @aeternam7 

Thank you for using my optimization library.

>any of your method allows this options?
Its similar features are not found in Nuget (1.8.1) and the "master" branch. 
I am organizing the code in the develop branch. It has a function that sets the value boundary.
However, it is to ensure that the result does not exceed the specified range. It does not accelerate convergence.

>i tested clsOptDE and gets a really accurate values, but does not converge so fast
I do not know the optimization algorithm used in nlminb. For example, if the Levenberg-Merguard or newton method is used, it converges quickly by the objective function.

DE is a heuristic algorithm. Looking for best result in populations(about 100~).
The library considers convergence when the group gets same result. If converting the value of CriterionRatio to a smaller value, convergence will be faster. However, it may not be the optimal solution.

```vb
        Dim optimization As New Optimization.DerivativeFree.DifferentialEvolution.DE_best_1_bin()
        optimization.ObjectiveFunction = New BenchSphere(2)
        optimization.UseCriterion = True
        optimization.CriterionRatio = 0.3 'default 0.7
        optimization.Init()
        optimization.DoIteration()
        Util.DebugValue(optimization)
```

**Comment by tomitomi3** [comment]
When you try the code, please switch to the develop branch.

**Comment by aeternam7** [comment]
thanks for your response

i'm using the binary LibOptimization.1.8.1

for DE, i can set the boundaries; in this kind of jobs -find the estimates of a GARCH(1,1) series- it is important to set the bondaries

DE of LibOptimization.1.8.1 is working good; i first use it to get the estimates of the model and then pass this values to a BFGS algorithm as initial values, to get the gradient and hessian, so i can compute the standard errors of the estimates

BFGS is unstable, so i can not use it as primary algorithm; i am using DE as primary algorithm

setting a good starting value is important for BFGS; probably it does not affect to DE algorithm

anyway, what is this for?

        Dim optimization2 As New Optimization.clsOptDE(fff)
        optimization2.IsUseCriterion = True
        'optimization2.DEStrategy = Optimization.clsOptDE.EnumDEStrategyType.DE_best_1_bin
        optimization2.LowerBounds = aLowerBounds
        optimization2.UpperBounds = aUpperBounds
¿¿>>optimization2.InitialPosition = aValoresIniciales <<<<<<<<<<<<<<<<<?????????????

i passed some starting values as InitialPosition but i know the algorithm does no use them to start iterating

thanks

**Comment by tomitomi3** [comment]
InitialPosition is a property that adds arbitrary initial values ​​to the group.
However, as you pointed out, this does not do what you intended. sorry...

**Comment by tomitomi3** [comment]
Add issues and fix it.

**Comment by tomitomi3** [comment]
I fixed the code. I also pushed to Nuget.

**Comment by aeternam7** [comment]
thanks a lot, it became a little bit faster adding an initial point near the converge solution

i saw this code in the VBSamples

            'do optimization
            optimization.DoIteration()
            If ErrorManage.IsRecentError() = True Then
                Console.WriteLine(ErrorManage.GetRecentError())
                Return
            End If

but i cannot access this class linking the library externally

i know the error type using Util.DebugValue(optimization), but that is only possible in a debuging enviroment

is it possible to know the error type -if this happened- when linking the library?

thanks in advance

**Comment by tomitomi3** [comment]
>but i cannot access this class linking the library externally

ErrorManage is a static function. I do not think that it will be not seen from the externally.

>i know the error type using Util.DebugValue(optimization), but that is only possible in a debuging enviroment

Is it that evaluation values ​​can not be acquired?
For general usage, Check the recent error from ErrorManage and get the result with Result property.

**Comment by aeternam7** [comment]
ah, sorry, when i downloaded 1.9 version from VISUAL STUDIO MANAGE NUGET PACKAGES, it didnt recognize ErrorManage and Util classes

now i referenced the library from _BuildLib folder and everything is ok

thanks again

**Comment by aeternam7** [comment]
sorry, tomi, but version 1.9 became faster but unstable; the algorithm i tested in 1.8.1 version was more stable

i'm testing for 1.9 version these types

                Dim optimizationDE As New Optimization.DerivativeFree.DifferentialEvolution.DE_best_1_bin
                Dim optimizationDE As New Optimization.DerivativeFree.DifferentialEvolution.DE_best_2_bin

so i came back to version 1.8.1, where DE alogrithm was initialized this way

                Dim optimizationDE As New Optimization.clsOptDE(fff)

which DE type must i use in version 1.9 to get the same resuts as 1.8.1 clsOptDE version

regards

**Comment by tomitomi3** [comment]
I am sorry for the confusion.
Please switch to master branch. It is a 1.9.0 library uploaded to Nuget.

master branch:
It is a library uploaded to Nuget.

develop branch:
develop ver.

>Dim optimizationDE As New Optimization.clsOptDE(fff)

DE has several strategies. The default strategy for 1.9.0 is DE_rand_1_bin. It has strong global searchability.
You can change the strategy with DEStrategy property.

DE_rand_~ : global searchability.

DE_best_~ : local searchability.

**Comment by aeternam7** [comment]
ok, DE_rand_2_bin is giving a very good stability

thanks again

**Comment by tomitomi3** [comment]
I am happy that I can help you.
