### ISSUE TITLE
Using LibOptimization

### ISSUE THREAD

**Issue by steph2000** [tomitomi3/LibOptimization#15]
Hello, 

I would like to use Liboptimization for a 2 variables function in my vb.net code.
I've coded my function f(x,y), but then, the syntax 
`Dim optimization As New clsOptDEJADE(New f( ))`
 is not correct, as the two parameters x and y are needed, and have to be declared. Could you give an example with a customize function please?

Kazu

**Comment by tomitomi3** [comment]
Thank you for using my library and I'm sorry late reply.

>the two parameters x and y are needed, and have to be declared. 
Set the objective function variable as an array argument.

e.g.
Objective function(sphere function):
<pre>
f(x1,x2)=x1^2 + x2^2
</pre>
Problem:
<pre>
min f
</pre>
Implement Objective function:
``` vb
Public Overrides Function F(x As List(Of Double)) As Double
    Return x(0)*x(0) + x(1)*x(1)
End Function
```

Refference:
https://github.com/tomitomi3/LibOptimization/issues/3#issuecomment-219233354
