### ISSUE TITLE
Integer overflow exception at absOptimization..ctor()

### ISSUE THREAD

**Issue by Worldexe** [tomitomi3/LibOptimization#9]
```
Namespace Optimization
    ...
    Public MustInherit Class absOptimization
        ...
        Protected m_rand As System.Random = New clsRandomXorshift(CUInt(Environment.TickCount))
```

`Environment.TickCount` can actually return negative number (it does at my machine).

There should be
`Protected m_rand As System.Random = New clsRandomXorshift(BitConverter.ToUInt32(BitConverter.GetBytes(Environment.TickCount), 0))`

**Comment by tomitomi3** [comment]
Thank you for finding the bug. When a negative number is an argument, exception is raised.
I fixed absOptimization in your code.
